server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

spring:
  config:
    import: optional:configserver:http://config-server:8888
  application:
    name: kafka-client
  cloud:
    config:
      fail-fast: true
