eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
server:
  port: 8765
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        -   id: kafka-client
            predicates:
              - Path=/kafka/*
              - Method=GET
            uri: lb://kafka-client
        -   id: rabbitmq-client
            predicates:
              - Path=/rabbitmq/*
              - Method=GET
            uri: lb://rabbitmq-client